tcp-addrs: ::1
tcp-port: 53
udp-addrs: ::1
udp-port: 53
log: yes
#log-file:
log-devel: WARNING
zone: example.jp
  source: zone/example.zone
  notify: yes
  notify-addrs: 127.0.0.1
  allow-notify: no
  allow-notify-addrs:
  allow-transfer: yes
  allow-transfer-addrs: ::1
  # for primary, aka reading source from a zone file
  dnssec: yes
  nsec3: yes
  key-dir: "/var/clove/keys/"
  pub-algo: ED25519
  ds-digest: SHA-256
  nsec3-hash: SHA-1
