local-zone: "z.example." static
local-data: 'a.z.example. 10800 192.0.2.9'
local-data: 't1.z.example. 10800 IN TXT "foo bar baz"'
local-data: 't2.z.example. 10800 IN TXT "foo bar" "baz"'

local-zone: "z.example." rediect
local-data: 'y.example. 10800 192.0.2.10'
