name: Haskell CI

on:
  push:
    branches: [ 'main', 'ci', 'ci-uc' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:  [ 'ubuntu-latest', 'macOS-latest' ]
        ghc: [ '9.2', '9.4', '9.6', '9.8', '9.10' ]

    env:
      cache-name: cabal-ghc
      target-config: --test-show-details=streaming --enable-tests --disable-benchmarks

    steps:
    - run: git config --global core.autocrlf false

    - uses: actions/checkout@v3

    - uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: latest

    - name: Hackage index, Cache Key
      id: params
      run: |
        ghc_version=$(ghc --numeric-version)
        cabal update
        echo "cache=${{ runner.os }}-build-${{ env.cache-name }}-${ghc_version}-v1-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}" > "$GITHUB_OUTPUT"
        echo "ghc_version=$ghc_version" >> "$GITHUB_OUTPUT"

    - name: Restore Cache
      uses: actions/cache/restore@v4
      if: ${{ github.ref_name != 'ci-uc' }}
      with:
        path: ~/.cabal
        key: ${{ steps.params.outputs.cache }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install doctest
      id: doctest-dep
      if: ${{ runner.os == 'Linux' }}
      run: |
        if cabal install --offline --overwrite-policy=always doctest
        then
          echo "installed=false" >> "$GITHUB_OUTPUT"
        else
          cabal install doctest --overwrite-policy=always
          echo "installed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Install dependencies
      id: inst-dep
      run: |
        if cabal build --offline --only-dependencies ${{ env.target-config }} all
        then
          echo "installed=false" >> "$GITHUB_OUTPUT"
        else
          cabal build --only-dependencies ${{ env.target-config }} all
          echo "installed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Save Cache
      uses: actions/cache/save@v4
      if: ${{ steps.inst-dep.outputs.installed == 'true' || steps.doctest-dep.outputs.installed == 'true' }}
      with:
        path: ~/.cabal
        key: ${{ steps.params.outputs.cache }}

    - name: Build
      run: cabal build ${{ env.target-config }} all

    - name: Run tests
      run: env DISABLE_V6_NS=1 cabal test ${{ env.target-config }} all

    - name: Run doctest
      if: ${{ runner.os == 'Linux' }}
      run: |
        for package in $(cat cabal.project | sed 's/packages://g' | sed 's/dnsext-bowline//g')
        do
          env DISABLE_V6_NS=1 cabal repl --with-ghc=doctest ${{ env.target-config }} $package
        done
        env   DISABLE_V6_NS=1 cabal repl --with-ghc=doctest ${{ env.target-config }} dnsext-bowline:bowline
